{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Real Time Voice Cloning\n",
    "\n",
    "With this example, we will submit a sample batch processing job to SageMaker. Make sure your run ./scripts/install.sh first. If you have the AWS CLI installed, you should be able to run this notebook locally. The transform() task however, will still run in the cloud on a GPU instance."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "bucket_name = 'real-time-voice-cloning'              # <-- Your bucket name goes here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import boto3\n",
    "import sagemaker as sage\n",
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "sess = sage.Session()\n",
    "account = sess.boto_session.client('sts').get_caller_identity()['Account']\n",
    "region = sess.boto_session.region_name\n",
    "trans = sage.transformer.Transformer('voice-cloning-recall', 1, 'ml.m5.xlarge')\n",
    "s3 = boto3.resource('s3')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Sample Job\n",
    "\n",
    "Here, we setup our batch processing job to clone two sample voices. Let's have Darth Vader and Morgan Freeman read some novel passages. Of course, you could do this with different utterance files or text."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "hp_text = [\"Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much.\",\n",
    "           \"They were the last people you'd expect to be involved in anything strange or mysterious, because they just didn't hold with such nonsense.\",\n",
    "           \"Mr. Dursley was the director of a firm called Grunnings, which made drills.\",\n",
    "           \"He was a big, beefy man with hardly any neck, although he did have a very large mustache.\",\n",
    "           \"Mrs. Dursley was thin and blonde and had nearly twice the usual amount of neck, which came in very useful as she spent so much of her time craning over garden fences, spying on the neighbors.\",\n",
    "           \"The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere.\"\n",
    "          ]\n",
    "\n",
    "two_cities_text = [\"It was the best of times, it was the worst of times\",\n",
    "                   \"it was the age of wisdom, it was the age of foolishness\",\n",
    "                   \"it was the epoch of belief, it was the epoch of incredulity\"\n",
    "                  ]\n",
    "\n",
    "job_json = {}\n",
    "job_json['request_id'] = 'test'\n",
    "job_json['request_type'] = 'batch_processing'\n",
    "\n",
    "job1 = {}\n",
    "job1['job_id'] = 'freeman_hp'\n",
    "job1['bucket'] = bucket_name\n",
    "job1['utterance_file'] = 'ssre-normal.wav'\n",
    "job1['sentences'] = hp_text\n",
    "\n",
    "job2 = {}\n",
    "job2['job_id'] = 'freeman_two_cities'\n",
    "job2['bucket'] = bucket_name\n",
    "job2['utterance_file'] = 'ssre-normal.wav'\n",
    "job2['sentences'] = two_cities_text\n",
    "\n",
    "job3 = {}\n",
    "job3['job_id'] = 'vader_hp'\n",
    "job3['bucket'] = bucket_name\n",
    "job3['utterance_file'] = 'darth.mp3'\n",
    "job3['sentences'] = hp_text\n",
    "\n",
    "job4 = {}\n",
    "job4['job_id'] = 'vader_two_cities'\n",
    "job4['bucket'] = bucket_name\n",
    "job4['utterance_file'] = 'darth.mp3'\n",
    "job4['sentences'] = two_cities_text\n",
    "\n",
    "job_json['jobs'] = [job1, job2, job3, job4]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Add our job as a json file to S3\n",
    "with open('./data/sample_job.json', 'w') as f:\n",
    "    f.write(json.dumps(job_json, indent=4))\n",
    "\n",
    "s3.Object(bucket_name, 'sample_job.json').upload_file('./data/sample_job.json')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ".....................\u001b[34m2020/07/04 22:25:30 [notice] 10#10: using the \"epoll\" event method\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:30 [notice] 10#10: nginx/1.14.0 (Ubuntu)\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:30 [notice] 10#10: OS: Linux 4.14.177-107.254.amzn1.x86_64\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:30 [notice] 10#10: getrlimit(RLIMIT_NOFILE): 65536:99999\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:30 [notice] 10#10: start worker processes\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:30 [notice] 10#10: start worker process 12\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:30 [crit] 12#12: *1 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: \"GET /ping HTTP/1.1\", upstream: \"http://unix:/tmp/gunicorn.sock:/ping\", host: \"169.254.255.131:8080\"\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [04/Jul/2020:22:25:30 +0000] \"GET /ping HTTP/1.1\" 502 182 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:30 [crit] 12#12: *3 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: \"GET /ping HTTP/1.1\", upstream: \"http://unix:/tmp/gunicorn.sock:/ping\", host: \"169.254.255.131:8080\"\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [04/Jul/2020:22:25:30 +0000] \"GET /ping HTTP/1.1\" 502 182 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:30 +0000] [11] [INFO] Starting gunicorn 20.0.4\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:30 +0000] [11] [INFO] Listening at: unix:/tmp/gunicorn.sock (11)\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:30 +0000] [11] [INFO] Using worker: gevent\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:30 +0000] [15] [INFO] Booting worker with pid: 15\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:30 +0000] [16] [INFO] Booting worker with pid: 16\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:30 +0000] [17] [INFO] Booting worker with pid: 17\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:30 +0000] [18] [INFO] Booting worker with pid: 18\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.\n",
      "\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.\n",
      "\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.\n",
      "\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.\n",
      "\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.\u001b[0m\n",
      "\u001b[34mImport requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.\n",
      "  from numba.decorators import jit as optional_jit\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.\u001b[0m\n",
      "\u001b[34mImport of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.\n",
      "  from numba.decorators import jit as optional_jit\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:35 +0000] [17] [ERROR] Exception in worker process\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 583, in spawn_worker\n",
      "    worker.init_process()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/ggevent.py\", line 162, in init_process\n",
      "    super().init_process()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 119, in init_process\n",
      "    self.load_wsgi()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 144, in load_wsgi\n",
      "    self.wsgi = self.app.wsgi()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py\", line 67, in wsgi\n",
      "    self.callable = self.load()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 49, in load\n",
      "    return self.load_wsgiapp()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 39, in load_wsgiapp\n",
      "    return util.import_app(self.app_uri)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/util.py\", line 358, in import_app\n",
      "    mod = importlib.import_module(module)\n",
      "  File \"/opt/conda/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/program/wsgi.py\", line 1, in <module>\n",
      "    import process_voice as myapp\n",
      "  File \"/opt/program/process_voice.py\", line 28, in <module>\n",
      "    encoder.load_model(Path(encoder_model_path))\n",
      "  File \"/opt/program/encoder/inference.py\", line 33, in load_model\n",
      "    checkpoint = torch.load(weights_fpath)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 529, in load\n",
      "    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 702, in _legacy_load\n",
      "    result = unpickler.load()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 665, in persistent_load\n",
      "    deserialized_objects[root_key] = restore_location(obj, location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 156, in default_restore_location\n",
      "    result = fn(storage, location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 132, in _cuda_deserialize\n",
      "    device = validate_cuda_device(location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 116, in validate_cuda_device\n",
      "    raise RuntimeError('Attempting to deserialize object on a CUDA '\u001b[0m\n",
      "\u001b[34mRuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.\u001b[0m\n",
      "\u001b[34mImport requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.\n",
      "  from numba.decorators import jit as optional_jit\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.\u001b[0m\n",
      "\u001b[34mImport of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.\n",
      "  from numba.decorators import jit as optional_jit\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:35 +0000] [16] [ERROR] Exception in worker process\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 583, in spawn_worker\n",
      "    worker.init_process()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/ggevent.py\", line 162, in init_process\n",
      "    super().init_process()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 119, in init_process\n",
      "    self.load_wsgi()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 144, in load_wsgi\n",
      "    self.wsgi = self.app.wsgi()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py\", line 67, in wsgi\n",
      "    self.callable = self.load()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 49, in load\n",
      "    return self.load_wsgiapp()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 39, in load_wsgiapp\n",
      "    return util.import_app(self.app_uri)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/util.py\", line 358, in import_app\n",
      "    mod = importlib.import_module(module)\n",
      "  File \"/opt/conda/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/program/wsgi.py\", line 1, in <module>\n",
      "    import process_voice as myapp\n",
      "  File \"/opt/program/process_voice.py\", line 28, in <module>\n",
      "    encoder.load_model(Path(encoder_model_path))\n",
      "  File \"/opt/program/encoder/inference.py\", line 33, in load_model\n",
      "    checkpoint = torch.load(weights_fpath)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 529, in load\n",
      "    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 702, in _legacy_load\n",
      "    result = unpickler.load()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 665, in persistent_load\n",
      "    deserialized_objects[root_key] = restore_location(obj, location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 156, in default_restore_location\n",
      "    result = fn(storage, location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 132, in _cuda_deserialize\n",
      "    device = validate_cuda_device(location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 116, in validate_cuda_device\n",
      "    raise RuntimeError('Attempting to deserialize object on a CUDA '\u001b[0m\n",
      "\u001b[34mRuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:35 +0000] [16] [INFO] Worker exiting (pid: 16)\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:35 +0000] [17] [INFO] Worker exiting (pid: 17)\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.\u001b[0m\n",
      "\u001b[34mImport requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.\n",
      "  from numba.decorators import jit as optional_jit\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.\u001b[0m\n",
      "\u001b[34mImport of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.\n",
      "  from numba.decorators import jit as optional_jit\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:35 +0000] [15] [ERROR] Exception in worker process\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 583, in spawn_worker\n",
      "    worker.init_process()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/ggevent.py\", line 162, in init_process\n",
      "    super().init_process()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 119, in init_process\n",
      "    self.load_wsgi()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 144, in load_wsgi\n",
      "    self.wsgi = self.app.wsgi()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py\", line 67, in wsgi\n",
      "    self.callable = self.load()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 49, in load\n",
      "    return self.load_wsgiapp()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 39, in load_wsgiapp\n",
      "    return util.import_app(self.app_uri)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/util.py\", line 358, in import_app\n",
      "    mod = importlib.import_module(module)\n",
      "  File \"/opt/conda/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/program/wsgi.py\", line 1, in <module>\n",
      "    import process_voice as myapp\n",
      "  File \"/opt/program/process_voice.py\", line 28, in <module>\n",
      "    encoder.load_model(Path(encoder_model_path))\n",
      "  File \"/opt/program/encoder/inference.py\", line 33, in load_model\n",
      "    checkpoint = torch.load(weights_fpath)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 529, in load\n",
      "    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 702, in _legacy_load\n",
      "    result = unpickler.load()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 665, in persistent_load\n",
      "    deserialized_objects[root_key] = restore_location(obj, location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 156, in default_restore_location\n",
      "    result = fn(storage, location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 132, in _cuda_deserialize\n",
      "    device = validate_cuda_device(location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 116, in validate_cuda_device\n",
      "    raise RuntimeError('Attempting to deserialize object on a CUDA '\u001b[0m\n",
      "\u001b[34mRuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:35 +0000] [15] [INFO] Worker exiting (pid: 15)\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.\u001b[0m\n",
      "\u001b[34mImport requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.\n",
      "  from numba.decorators import jit as optional_jit\u001b[0m\n",
      "\u001b[34m/opt/conda/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.\u001b[0m\n",
      "\u001b[34mImport of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.\n",
      "  from numba.decorators import jit as optional_jit\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:35 +0000] [18] [ERROR] Exception in worker process\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 583, in spawn_worker\n",
      "    worker.init_process()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/ggevent.py\", line 162, in init_process\n",
      "    super().init_process()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 119, in init_process\n",
      "    self.load_wsgi()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py\", line 144, in load_wsgi\n",
      "    self.wsgi = self.app.wsgi()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py\", line 67, in wsgi\n",
      "    self.callable = self.load()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 49, in load\n",
      "    return self.load_wsgiapp()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 39, in load_wsgiapp\n",
      "    return util.import_app(self.app_uri)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/util.py\", line 358, in import_app\n",
      "    mod = importlib.import_module(module)\n",
      "  File \"/opt/conda/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/program/wsgi.py\", line 1, in <module>\n",
      "    import process_voice as myapp\n",
      "  File \"/opt/program/process_voice.py\", line 28, in <module>\n",
      "    encoder.load_model(Path(encoder_model_path))\n",
      "  File \"/opt/program/encoder/inference.py\", line 33, in load_model\n",
      "    checkpoint = torch.load(weights_fpath)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 529, in load\n",
      "    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 702, in _legacy_load\n",
      "    result = unpickler.load()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 665, in persistent_load\n",
      "    deserialized_objects[root_key] = restore_location(obj, location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 156, in default_restore_location\n",
      "    result = fn(storage, location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 132, in _cuda_deserialize\n",
      "    device = validate_cuda_device(location)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 116, in validate_cuda_device\n",
      "    raise RuntimeError('Attempting to deserialize object on a CUDA '\u001b[0m\n",
      "\u001b[34mRuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.\u001b[0m\n",
      "\u001b[34m[2020-07-04 22:25:35 +0000] [18] [INFO] Worker exiting (pid: 18)\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:36 [error] 12#12: *5 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 169.254.255.130, server: , request: \"GET /ping HTTP/1.1\", upstream: \"http://unix:/tmp/gunicorn.sock:/ping\", host: \"169.254.255.131:8080\"\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [04/Jul/2020:22:25:36 +0000] \"GET /ping HTTP/1.1\" 502 182 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 209, in run\n",
      "    self.sleep()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 357, in sleep\n",
      "    ready = select.select([self.PIPE[0]], [], [], 1.0)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 242, in handle_chld\n",
      "    self.reap_workers()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 525, in reap_workers\n",
      "    raise HaltServer(reason, self.WORKER_BOOT_ERROR)\u001b[0m\n",
      "\u001b[34mgunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>\n",
      "\u001b[0m\n",
      "\u001b[34mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/opt/conda/bin/gunicorn\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py\", line 58, in run\n",
      "    WSGIApplication(\"%(prog)s [OPTIONS] [APP_MODULE]\").run()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py\", line 228, in run\n",
      "    super().run()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py\", line 72, in run\n",
      "    Arbiter(self).run()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 229, in run\n",
      "    self.halt(reason=inst.reason, exit_status=inst.exit_status)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 342, in halt\n",
      "    self.stop()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 393, in stop\n",
      "    time.sleep(0.1)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 242, in handle_chld\n",
      "    self.reap_workers()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py\", line 525, in reap_workers\n",
      "    raise HaltServer(reason, self.WORKER_BOOT_ERROR)\u001b[0m\n",
      "\u001b[34mgunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:36 [notice] 10#10: signal 3 (SIGQUIT) received from 1, shutting down\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:36 [notice] 12#12: gracefully shutting down\u001b[0m\n",
      "\u001b[34mStarting the inference server with 4 workers.\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:36 [notice] 12#12: exiting\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:36 [notice] 12#12: exit\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:36 [notice] 10#10: signal 17 (SIGCHLD) received from 12\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:36 [notice] 10#10: worker process 12 exited with code 0\u001b[0m\n",
      "\u001b[34m2020/07/04 22:25:36 [notice] 10#10: exit\u001b[0m\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Start the job. It should take several minutes. Although most of that is from starting the container.\n",
    "trans.transform(f's3://{bucket_name}/sample_job.json', content_type='application/json')\n",
    "trans.wait()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# When the job is finished we should have all of the results files in S3. Here, we'll just download them.\n",
    "for f in s3.Bucket(bucket_name).objects.all():\n",
    "    file_name = f.key\n",
    "    if 'vader' in file_name or 'freeman' in file_name:\n",
    "        print(f'Downloading: {file_name}')\n",
    "        s3.Bucket(bucket_name).download_file(file_name, f'./data/{file_name}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'us-east-1'"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "region"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pythondata",
   "language": "python",
   "name": "pythondata"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
